/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as ProblemPsIdRouteImport } from './routes/problem.$psId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemPsIdRoute = ProblemPsIdRouteImport.update({
  id: '/problem/$psId',
  path: '/problem/$psId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shortlist': typeof ShortlistRoute
  '/problem/$psId': typeof ProblemPsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shortlist': typeof ShortlistRoute
  '/problem/$psId': typeof ProblemPsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shortlist': typeof ShortlistRoute
  '/problem/$psId': typeof ProblemPsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shortlist' | '/problem/$psId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shortlist' | '/problem/$psId'
  id: '__root__' | '/' | '/shortlist' | '/problem/$psId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortlistRoute: typeof ShortlistRoute
  ProblemPsIdRoute: typeof ProblemPsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem/$psId': {
      id: '/problem/$psId'
      path: '/problem/$psId'
      fullPath: '/problem/$psId'
      preLoaderRoute: typeof ProblemPsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortlistRoute: ShortlistRoute,
  ProblemPsIdRoute: ProblemPsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
